name: Build TWRP/OFRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Recovery

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y git bc bison build-essential curl flex g++-multilib \
          gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
          lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev \
          libssl-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools \
          xsltproc zip zlib1g-dev openjdk-8-jdk wget unzip

      - name: Set up Repo tool
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          echo "PATH=$PATH:~/bin" >> $GITHUB_ENV

      - name: Initialize repo and sync
        run: |
          mkdir workspace && cd workspace
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          repo init -u https://github.com/OrangeFoxRecovery/manifest -b fox_12.1 --depth=1
          mkdir -p .repo/local_manifests
          cat > .repo/local_manifests/gold.xml <<EOF
          <manifest>
            <project name="zirvepaul/android_device_xiaomi_gold__" path="device/xiaomi/gold" remote="github" revision="main" />
          </manifest>
          EOF
          repo sync -j$(nproc) || repo sync -j1

      - name: Build recovery
        run: |
          cd workspace
          source build/envsetup.sh
          lunch omni_gold-eng
          mka recoveryimage

      - name: Upload recovery image
        uses: actions/upload-artifact@v3
        with:
          name: recovery.img
          path: workspace/out/target/product/gold/recovery.img
